---

- hosts: localhost
  gather_facts: yes
  tasks:
    - name: Add Oracle VirtualBox repository key
      ansible.builtin.apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - name: Add Oracle VirtualBox repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
        state: present

    - name: Install VirtualBox 7
      apt:
        name: virtualbox-7.0
        state: present

    - name: Download VirtualBox Extension Pack
      get_url:
        url: "{{ virtualbox_ext_pack_url }}/{{ virtualbox_ext_pack }}"
        dest: /tmp/{{ virtualbox_ext_pack }}
        force: true

    - name: Install VirtualBox Extension Pack
      command: vboxmanage extpack install /tmp/{{ virtualbox_ext_pack }} --accept-license={{ virtualbox_ext_pack_license_hash }}

    - name: install docker
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
        state: present
        force_apt_get: yes

    # add user to docker group to run docker commands without sudo
    # add user to vboxusers group so that user can attach usb devices to guest OS
    - name: add user to vboxusers groups
      ansible.builtin.user:
        name: "{{ local_username }}"
        append: yes
        groups:
          - vboxusers
          - docker

...
