---
# add jumphost IP to the hosts file
- name: Add entry to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }}"
    state: present
    with_items:
      - { ip: "10.49.63.119", hostname: "eu-jump" }
      - { ip: "10.68.63.121", hostname: "us-jump" }